# 配置tomcat端口号
server:
  port: 9091

# 配置数据源
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boottest
    username: root
    password: 123456test!
  application:
    name: user-service

# 配置mybatis
mybatis:
  # 配置类型别名包扫描
  type-aliases-package: com.freedom.user.pojo
  # 配置sql语句映射文件路径
  mapper-locations:
    - classpath:mappers/*.xml
  # 驼峰映射
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    #更倾向于使用IP而非host
    prefer-ip-address: true
    #IP地址
    ip-address: 127.0.0.1
    #续约间隔，默认30秒
    lease-renewal-interval-in-seconds: 5
    #服务失效时间，默认90秒
    lease-expiration-duration-in-seconds: 5