# 配置tomcat端口号
server:
  port: 9091

# 配置数据源
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boottest
    username: root
    password: 123456test!
  application:
    name: user-service

# 配置mybatis
mybatis:
  # 配置类型别名包扫描
  type-aliases-package: com.freedom.user.pojo
  # 配置sql语句映射文件路径
  mapper-locations:
    - classpath:mappers/*.xml
  # 驼峰映射
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka