# 配置tomcat端口号
server:
  port: ${port:10086}
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      # eureka 服务地址，如果是集群的话；需要指定其它集群eureka地址
      defaultZone: ${defaultZone:http://127.0.0.1:10086/eureka}
    # 不注册自己
#    register-with-eureka: false
    # 不拉取服务
#    fetch-registry: false
    #拉取服务时间间隔，单位
    registry-fetch-interval-seconds: 5
    #服务失效剔除时间
  server:
    eviction-interval-timer-in-ms: 5
    #关闭自我保护模式
    enable-self-preservation: false

  #关闭自我保护模式




